name: Waka Readme

on:
  workflow_dispatch:
  schedule:
  # Roda as 12am
  - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Atualiza minhas metricas no README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en" # English msm pra manter o padrao do readme :)
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"